server:
  port: 8087

spring:
  thymeleaf:
    cache: false

iw:
  client-console:
    gateway-url: ${GATEWAY_URL:http://localhost:8080}
    request-timeout: 40s
    session:
      cookie-name: iw_client
      secure: false
