spring:
  kafka:
    bootstrap-servers: kafka:9092
  data:
    mongodb:
      uri: mongodb://mongo:27017/iw_telemetry
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8081/api/v1/auth/.well-known/jwks.json
